### ISSUE TITLE
複数ドメインに対応した証明書を作ろうとするとバリデーションでエラーが起きる

### ISSUE THREAD

**Issue by FujiHaruka** [realglobe-Inc/terraform-aws-acm-certificate#6]
たとえば `domain_names = ["example.jp", "*.foo.example.jp"]` を作りたいときに、二番目のドメインのバリデーションでエラーになる。

```console
$ terraform apply

...

Error: [ERR]: Error building changeset: InvalidChangeBatch: [Tried to create resource record set [name='_488ad0efd495aaa63f57cef7aa98d390.foo.example.com.', type='CNAME'] but it already exists]
	status code: 400, request id: 4d3db92a-bb19-4ba7-ab1a-0e08ec803558

```

**Comment by s-oku** [comment]
これはワイルドカード証明書の検証レコードが`*.`なしのやつと同じだからっぽい。
`Tried to create resource ... but it already exists`とか言ってるし、`terraform import`してどうにかする。

**Comment by FujiHaruka** [comment]
ワイルドカードを domain_names に含めなければいいみたいですね。とりま運用でカバーします。

**Comment by s-oku** [comment]
多分ワイルドカードでも1つだけなら問題ないと思うんですが、

- `foo.example.com`と`*.foo.example.com`の両方に対応した証明書を作る
- `foo.example.com`がすでにある時に`*.foo.example.com`の証明書を作る
  - またはその逆

みたいな時に両方とも検証用のDNSレコードが同じになって、同じレコードを作成しようとしてエラーになるんじゃないかと思います。
